// src/components/Calculator.tsx
'use client';

import {
  Grid,
  TextField,
  Button,
  Checkbox,
  FormControlLabel,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Typography,
  Chip,
  Box,
  InputAdornment,
} from '@mui/material';
import { useState, useRef } from 'react';

const Calculator = () => {
  const [capital, setCapital] = useState(120000);
  const [annualExpense, setAnnualExpense] = useState(20000);
  const [dividendYield, setDividendYield] = useState(4);
  const [dividendGrowthRate, setDividendGrowthRate] = useState(20);
  const [dividendTaxRate, setDividendTaxRate] = useState(30);
  const [inflationRate, setInflationRate] = useState(3);
  const [isReinvesting, setIsReinvesting] = useState(true);
  const [dividendsSummary, setDividendsSummary] = useState(null);
  const dt = useRef(null);

  const calculate = (e) => {
    e.preventDefault();
    let tempCapital = capital;
    const summary = [];

    for (let i = 0; i < 15; i++) {
      const currentDividendYield =
        (dividendYield * Math.pow(1 + dividendGrowthRate / 100, i)) / 100;
      const annualDividends =
        tempCapital * currentDividendYield * (1 - dividendTaxRate / 100);

      summary.push({
        year: i + 1,
        annualDividends,
        dividendYield: currentDividendYield,
        monthlyExpense:
          (annualExpense / 12) * Math.pow(1 + inflationRate / 100, i),
        monthlyDividends: annualDividends / 12,
      });

      if (isReinvesting) {
        tempCapital += annualDividends;
      }
    }
    setDividendsSummary(summary);
  };

  const formatCurrency = (value) => {
    return value.toLocaleString('en-US', {
      style: 'currency',
      currency: 'USD',
    });
  };

  const formatPercent = (value) => {
    return value.toLocaleString('en-US', {
      style: 'percent',
      minimumFractionDigits: 2,
    });
  };

  const exportCSV = () => {
    const headers = [
      'Year',
      'Annual Dividends (After Tax)',
      'Dividend Yield',
      'Monthly Expense',
      'Monthly Dividends (After Tax)',
      'FIRE',
    ];
    const rows = dividendsSummary.map((row) => [
      row.year,
      formatCurrency(row.annualDividends),
      formatPercent(row.dividendYield),
      formatCurrency(row.monthlyExpense),
      formatCurrency(row.monthlyDividends),
      row.monthlyDividends < row.monthlyExpense ? 'No' : 'Yes',
    ]);

    let csvContent = 'data:text/csv;charset=utf-8,';
    csvContent += headers.join(',') + '\r\n';
    rows.forEach((row) => {
      csvContent += row.join(',') + '\r\n';
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', 'Summary of Return.csv');
    document.body.appendChild(link);
    link.click();
  };

  return (
    <Box>
      <Typography variant="h4">
        FIRE Calculator
      </Typography>
      <Box component="form" onSubmit={calculate} sx={{ mb: 4 }}>
        <Grid container spacing={2}>
          <Grid size={6}>
            <TextField
              label="Capital"
              type="number"
              value={capital}
              onChange={(e) => setCapital(parseFloat(e.target.value))}
              fullWidth
              required
            />
          </Grid>
          <Grid size={6}>
            <TextField
              label="Annual Expense"
              type="number"
              value={annualExpense}
              onChange={(e) => setAnnualExpense(parseFloat(e.target.value))}
              fullWidth
              required
            />
          </Grid>
          <Grid size={{ xs: 6, md: 3 }}>
            <TextField
              label="Dividend Yield"
              type="number"
              value={dividendYield}
              onChange={(e) => setDividendYield(parseFloat(e.target.value))}
              fullWidth
              required
              slotProps={{
                input: {
                  endAdornment: <InputAdornment position="end">%</InputAdornment>,
                },
              }}
            />
          </Grid>
          <Grid size={{ xs: 6, md: 3 }}>
            <TextField
              label="Dividend Growth Rate"
              type="number"
              value={dividendGrowthRate}
              onChange={(e) => setDividendGrowthRate(parseFloat(e.target.value))}
              fullWidth
              required
              slotProps={{
                input: {
                  endAdornment: <InputAdornment position="end">%</InputAdornment>,
                },
              }}
            />
          </Grid>
          <Grid size={{ xs: 6, md: 3 }}>
            <TextField
              label="Dividend Tax Rate"
              type="number"
              value={dividendTaxRate}
              onChange={(e) => setDividendTaxRate(parseFloat(e.target.value))}
              fullWidth
              required
              slotProps={{
                input: {
                  endAdornment: <InputAdornment position="end">%</InputAdornment>,
                },
              }}
            />
          </Grid>
          <Grid size={{ xs: 6, md: 3 }}>
            <TextField
              label="Inflation Rate"
              type="number"
              value={inflationRate}
              onChange={(e) => setInflationRate(parseFloat(e.target.value))}
              fullWidth
              required
              slotProps={{
                input: {
                  endAdornment: <InputAdornment position="end">%</InputAdornment>,
                },
              }}
            />
          </Grid>
          <Grid size={12}>
            <FormControlLabel
              control={<Checkbox checked={isReinvesting} onChange={(e) => setIsReinvesting(e.target.checked)} />}
              label="Reinvesting dividends annually?"
            />
          </Grid>
          <Grid size={12}>
            <Button type="submit" className="fire-calculator__submit" variant="contained" color="primary" size="large" fullWidth>
              Calculate
            </Button>
          </Grid>
        </Grid>
      </Box>

      {dividendsSummary && (
        <Grid container>
          <Grid size={12}>
            <Paper elevation={3}>
              <Box sx={{ display: 'flex', justifyContent: 'flex-end', p: 2 }}>
                <Button className="fire-calculator__export" onClick={exportCSV} variant="contained">
                  Export
                </Button>
              </Box>
              <TableContainer ref={dt}>
                <Table>
                  <TableHead>
                    <TableRow>
                      <TableCell>Year</TableCell>
                      <TableCell>Annual Dividends (After Tax)</TableCell>
                      <TableCell>Dividend Yield</TableCell>
                      <TableCell>Monthly Expense</TableCell>
                      <TableCell>Monthly Dividends (After Tax)</TableCell>
                      <TableCell>FIRE</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {dividendsSummary.map((row) => (
                      <TableRow key={row.year}>
                        <TableCell>{row.year}</TableCell>
                        <TableCell>{formatCurrency(row.annualDividends)}</TableCell>
                        <TableCell>{formatPercent(row.dividendYield)}</TableCell>
                        <TableCell>{formatCurrency(row.monthlyExpense)}</TableCell>
                        <TableCell>{formatCurrency(row.monthlyDividends)}</TableCell>
                        <TableCell>
                          <Chip
                            label={row.monthlyDividends < row.monthlyExpense ? 'No' : 'Yes'}
                            color={row.monthlyDividends < row.monthlyExpense ? 'error' : 'success'}
                          />
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            </Paper>
          </Grid>
        </Grid>
      )}
    </Box >
  );
};

export default Calculator;

// src/components/Calculator.vue
<template>
  <h5>FIRE Calculator</h5>

  <div class="p-grid">
    <div class="p-col-12">
      <form class="fire-calculator" @submit.prevent="calculate">

        <div class="p-grid p-fluid">
          <div class="p-col-6">
            <div class="p-field">
              <label for="capital">Capital</label>
              <div class="p-inputgroup">
                <InputNumber v-model="capital" id="capital" placeholder="e.g. 200000" :min="0" mode="currency"
                             currency="USD" locale="en-US" required />
              </div>
            </div>
          </div>
          <div class="p-col-6">
            <div class="p-field">
              <label for="annual-expense">Annual Expense</label>
              <div class="p-inputgroup">
                <InputNumber v-model="annualExpense" id="annual-expense" placeholder="e.g. 100000" :min="0"
                             mode="currency" currency="USD" locale="en-US" required />
              </div>
            </div>
          </div>
          <div class="p-col-6 p-md-3">
            <div class="p-field">
              <label for="dividend-yield">Dividend Yield</label>
              <div class="p-inputgroup">
                <InputNumber v-model="dividendYield" id="dividend-yield" placeholder="e.g. 4.00%" suffix="%" :min="0"
                             :max="100" mode="decimal" :minFractionDigits="2" :maxFractionDigits="2" required />
              </div>
            </div>
          </div>
          <div class="p-col-6 p-md-3">
            <div class="p-field">
              <label for="dividend-growth-rate">Dividend Growth Rate</label>
              <div class="p-inputgroup">
                <InputNumber v-model="dividendGrowthRate" id="dividend-growth-rate" placeholder="e.g. 20.00%" suffix="%"
                             :min="0" :max="100" mode="decimal" :minFractionDigits="2" :maxFractionDigits="2"
                             required />
              </div>
            </div>
          </div>
          <div class="p-col-6 p-md-3">
            <div class="p-field">
              <label for="dividend-tax-rate">Dividend Tax Rate</label>
              <div class="p-inputgroup">
                <InputNumber v-model="dividendTaxRate" id="dividend-tax-rate" placeholder="e.g. 30.00%" suffix="%"
                             :min="0" :max="100" mode="decimal" :minFractionDigits="2" :maxFractionDigits="2"
                             required />
              </div>
            </div>
          </div>

          <div class="p-col-6 p-md-3">
            <div class="p-field">
              <label for="inflation-rate">Inflation Rate</label>
              <div class="p-inputgroup">
                <InputNumber v-model="inflationRate" id="inflation-rate" placeholder="e.g. 3.00%" suffix="%" :min="0"
                             :max="100" mode="decimal" :minFractionDigits="2" :maxFractionDigits="2" required />
              </div>
            </div>
          </div>

          <div class="p-col-12">
            <div class="p-field-checkbox">
              <Checkbox v-model="isReinvesting" id="is-reinvesting" :binary="true" />
              <label for="is-reinvesting">Reinvesting dividends annually?</label>
            </div>
          </div>

          <div class="p-col">
            <Button class="fire-calculator__submit" type="submit" label="Calculate" />
          </div>
        </div>
      </form>
    </div>

    <div class="p-col-12" v-if="dividendsSummary">
      <DataTable ref="table" exportFilename="Summary of Return" :value="dividendsSummary">
        <template #header>
          <div class="p-text-right">
            <Button class="fire-calculator__export" icon="pi pi-external-link" label="Export"
                    @click="exportCSV($event)" />
          </div>
        </template>
        <Column field="year" header="Year"></Column>
        <Column field="annualDividends" header="Annual Dividends (After Tax)">
          <template #body="slotProps">
            {{formatCurrency(slotProps.data.annualDividends)}}
          </template>
        </Column>
        <Column field="dividendYield" header="Dividend Yield">
          <template #body="slotProps">
            {{formatPercent(slotProps.data.dividendYield)}}
          </template>
        </Column>
        <Column field="monthlyExpense" header="Monthly Expense">
          <template #body="slotProps">
            {{formatCurrency(slotProps.data.monthlyExpense)}}
          </template>
        </Column>
        <Column field="monthlyDividends" header="Monthly Dividends (After Tax)">
          <template #body="slotProps">
            {{formatCurrency(slotProps.data.monthlyDividends)}}
          </template>
        </Column>
        <Column header="FIRE">
          <template #body="slotProps">
            <Badge :value="slotProps.data.monthlyDividends < slotProps.data.monthlyExpense ? 'No' : 'Yes' "
                   :severity="slotProps.data.monthlyDividends < slotProps.data.monthlyExpense ? 'danger' : 'success' ">
            </Badge>
          </template>
        </Column>
      </DataTable>
    </div>
  </div>
</template>


<script>
export default {
  name: 'Calculator',
  data() {
    return {
      numYears: 15,
      capital: 120000,
      annualExpense: 20000,
      dividendYield: 4,
      dividendGrowthRate: 20,
      dividendTaxRate: 30,
      inflationRate: 3,
      isReinvesting: true,
      dividendsSummary: null,
    };
  },
  methods: {
    calculate() {
      let capital = this.capital;
      this.dividendsSummary = [];

      for (let i = 0; i < this.numYears; i++) {
        const dividendYield =
          (this.dividendYield *
            Math.pow(1 + this.dividendGrowthRate / 100, i)) /
          100;
        const annualDividends =
          capital * dividendYield * (1 - this.dividendTaxRate / 100);

        this.dividendsSummary.push({
          year: i + 1,
          annualDividends,
          dividendYield,
          monthlyExpense:
            (this.annualExpense / 12) *
            Math.pow(1 + this.inflationRate / 100, i),
          monthlyDividends: annualDividends / 12,
        });

        if (this.isReinvesting) {
          capital += annualDividends;
        }
      }
    },

    formatCurrency(value) {
      return value.toLocaleString('en-US', {
        style: 'currency',
        currency: 'USD',
      });
    },
    formatPercent(value) {
      return value.toLocaleString('en-US', {
        style: 'percent',
        minimumFractionDigits: 2,
      });
    },
    exportCSV() {
      this.$refs.table.exportCSV();
    },
  },
};
</script>

<style lang="scss">
</style>
