// src/components/Footer.tsx
const Footer = () => {
  return (
    <footer>
      <div className="copyright">
        <span>Designed & Created by </span>
        <a href="https://peterwong.me" target="_blank" rel="noreferrer">Peter Wong</a>
        <span> © {new Date().getFullYear()}</span>
      </div>
    </footer>
  );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer>
    <div class="copyright">
      Designed &amp; Created by
      <a href="https://peterwong.me" target="_blank">Peter Wong</a>
      © {{ new Date().getFullYear() }}
    </div>
  </footer>
</template>


<script>
export default {
  name: 'Footer',
};
</script>

<style lang="scss">
footer {
  padding: 1rem;
  font-size: 80%;
  color: #fff;
  background-color: #88c5cc;
  text-align: center;

  a {
    color: #fff;
    text-decoration: none;
  }
}
</style>
